// Generated by CoffeeScript 1.8.0
var jade, jadeify;

jade = require('gulp-jade');

jadeify = require('jadeify');

module.exports = function(Parched) {
  return Parched.createPlugin({
    displayName: 'parched-jade',
    src: '*.jade',
    modifyBundleOptions: function(bundleOptions) {
      return bundleOptions.extensions.push('.jade');
    },
    modifyBrowserifyObject: function(b) {
      return b.transform(jadeify);
    },
    getDefaultOptions: function() {
      return {
        pretty: !this.isProduction(),
        runtimePath: require.resolve(require.resolve('jade/runtime'))
      };
    },
    transform: function() {
      return jade(this.options);
    }
  });
};
