// Generated by CoffeeScript 1.8.0
var less;

less = require('gulp-less');

module.exports = function(Parched) {
  return Parched.createPlugin({
    displayName: 'parched-less',
    src: '*.less',
    transform: function() {
      return less(this.options);
    }
  });
};
