// Generated by CoffeeScript 1.8.0
var CSSBuilder, SpriteBuilder;

SpriteBuilder = require('./sprite-builder');

CSSBuilder = require('./css-builder');

module.exports = function(Parched) {
  return Parched.createPlugin({
    displayName: 'parched-svg2png',
    src: '*.svg',
    shouldProcessAssets: function() {
      return true;
    },
    getDefaultOptions: function() {
      return {
        src: 'sprites/**/*.svg',
        outputCSS: 'app/styles/sprites.css',
        outputImage: 'public/images/sprite-map.png',
        usePlaceholderSelectors: true,
        cssClassPrefix: 's',
        httpImagesPath: '/images/'
      };
    },
    transform: function(context) {
      var optionsClone;
      optionsClone = Parched.vendor.xtend({}, this.options);
      return this.processManyFiles(optionsClone.src, context, function(files, done) {
        var cssBuilder, spriteBuilder;
        optionsClone.files = files;
        cssBuilder = new CSSBuilder(optionsClone);
        cssBuilder.done = done;
        spriteBuilder = new SpriteBuilder(optionsClone);
        spriteBuilder.done = function(err) {
          if (err) {
            return done(err);
          }
          return cssBuilder.build();
        };
        return spriteBuilder.build();
      });
    }
  });
};
