// Generated by CoffeeScript 1.8.0
var csslint;

csslint = require('gulp-csslint');

module.exports = function(P) {
  return P.createPlugin({
    displayName: 'parched-csslint',
    src: '*.css',
    lint: function() {
      var stream;
      stream = [csslint(this.options), csslint.reporter()];
      if (this.isProduction()) {
        stream.push(csslint.reporter(csslint.failReporter));
      }
      return stream;
    }
  });
};
