// Generated by CoffeeScript 1.8.0
var jshint, stylish;

jshint = require('gulp-jshint');

stylish = require('jshint-stylish');

module.exports = function(P) {
  return P.createPlugin({
    displayName: 'parched-jshint',
    src: '*.js',
    lint: function() {
      var stream;
      stream = [jshint(this.options), jshint.reporter(stylish)];
      if (this.isProduction()) {
        stream.push(jshint.reporter('fail'));
      }
      return stream;
    }
  });
};
