// Generated by CoffeeScript 1.8.0
var coffee, coffeeify;

coffee = require('gulp-coffee');

coffeeify = require('coffeeify');

module.exports = function(Parched) {
  return Parched.createPlugin({
    displayName: 'parched-coffee-script',
    src: '*.coffee',
    modifyBundleOptions: function(bundleOptions) {
      bundleOptions.extensions.push('.coffee', '.litcoffee');
    },
    modifyBrowserifyObject: function(b) {
      b.transform(coffeeify);
    },
    transform: function() {
      return coffee(this.options);
    }
  });
};
