// Generated by CoffeeScript 1.8.0
var cssmin;

cssmin = require('gulp-cssmin');

module.exports = function(Parched) {
  return Parched.createPlugin({
    displayName: 'parched-minify-css',
    src: '*.css',
    minify: function() {
      return cssmin(this.options);
    }
  });
};
