// Generated by CoffeeScript 1.8.0
var minifyCSS;

minifyCSS = require('gulp-minify-css');

module.exports = function(Parched) {
  return Parched.createPlugin({
    displayName: 'parched-minify-css',
    src: '*.css',
    minify: function() {
      return minifyCSS(this.options);
    }
  });
};
