// Generated by CoffeeScript 1.8.0
var sass;

sass = require('gulp-sass');

module.exports = function(P) {
  return P.createPlugin({
    displayName: 'parched-sass',
    src: ['*.sass', '*.scss'],

    getDefaultOptions: function() {
      return {
        sourceComments: 'normal',
        indentedSyntax: true,
      };
    },

    transform: function() {
      return sass(this.options);
    }
  });
};
